### PR TITLE
Update to latest pluginator version to fix bug with bundler 1.15

### LINKED ISSUE #258: Bundler 1.15.0 incompatibility
It's a fault of the `pluginator` dependency, I'm writing just for the record. See rvm/pluginator/issues/10.

### PR DESCRIPTION
**Pull request by mpapis**
Fixes #258

### CODE REVIEW

**Comment by mpapis** [comment]
interesting, the tests fail only when ran via `rake`

**Comment by mpapis** [comment]
the tests fail because one of the loaded tests is detected as a plugin, I hope to work on it today, but it should be safe to merge & release right away, I will release a new version with fix for tests soon

**Comment by mpapis** [comment]
@jish it's fixed now with 1.5.0

**Comment by jish** [comment]
Thanks!

**Pull request merged**
