### PR TITLE
Adding checks for byebug in same fashion as debugger

### PR DESCRIPTION
**Pull request by prpetten**
This pull request addresses issue #206

### CODE REVIEW

**Comment by jish** [comment]
This looks good, thanks. Do you think we should combine the `debugger` and `byebug` checks? Or would it make sense to have them separate?

cc: @shajith @mpapis

**Comment by mpapis** [comment]
we should merge them, it's just adding `|` in the regexp and updating description to say `or byebug`

**Comment by prpetten** [comment]
Sounds good, I'll merge them, just didn't know what you guys would prefer.

**Comment by jclif** [comment]
Any plans to merge this?

**Comment by mpapis** [comment]
we are still waiting for the merge of plugins ... @jclif if you are in hurry clone @prpetten repository, merge the plugins and open a new pull request

**Comment by jclif** [comment]
@mpapis thanks, will try that

**Comment by prpetten** [comment]
@jclif Let me know if you need any help.  I just haven't had a chance to work on again.

**Comment by jish** [comment]
https://github.com/jish/pre-commit/pull/224

**Pull request closed without merging**
