### PR TITLE
Add pry-remote/pry-remote-em to Pry checks

### PR DESCRIPTION
**Pull request by m1foley**
pry-remote/pry-remote-em are common plugins for Pry.

https://github.com/pry/pry/wiki/Available-plugins

### CODE REVIEW

**Comment by mpapis** [comment]
:+1:

**Comment by jish** [comment]
Hmm... the tests seem to be failing. Once we get those sorted out, this looks fine.

**Comment by mpapis** [comment]
now on master you can:
```bash
pre-commit new plugin-name 'Author Name' author@email 'description of the plugin'
```
this will generate scaffold for your gem - should be easy to move it from this point on, please let me know if you find any more instructions that should be added (open a new issue).

**Comment by m1foley** [comment]
I believe this change is to granular to be made a separate `pry-remote` plugin; it should modify the existing `pry` check. Do you disagree?

**Comment by mpapis** [comment]
ah right, sorry, I was not looking deep enough before posting my comment

**Comment by m1foley** [comment]
Just rebased off master. Travis still says it's failing because tests are broken on master.

**Comment by mpapis** [comment]
master is green: https://travis-ci.org/jish/pre-commit/builds/107029409

the failure happens in case of jruby here: https://travis-ci.org/jish/pre-commit/jobs/110663827#L428 - it looks like parsing of the output is wrong, it does not split on new lines

**Comment by m1foley** [comment]
You're right, I needed to update the test.

I was thrown off because `bundle exec rake` produces 6 failures for me locally.

**Comment by mpapis** [comment]
LGTM

**Comment by jish** [comment]
Thanks for your contribution!

**Pull request merged**
